baseurl: "https://blog.chungzh.cn"
languageCode: "zh-cn"
title: "Zirnc's Blog"
#theme: "hugo-tania"
theme: "hugo-bearblog"

# disqusShortname: https-hugo-tania-netlify-app

permalinks:
  articles: "/:slug/"
  tags: "/blog/:slug"

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 🎆

  # Logo will show before the blog title on site navbar.
  titleLogo: BlogFavicon16.png

  favicon: BlogFavicon16.png
  
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus
    giscus:
        repo: ChungZH/ChungZH.github.io
        id: MDEwOlJlcG9zaXRvcnkxNzcxMjMzNjI=
        category:
            name: Comments
            id: DIC_kwDOCo6wIs4B_i5g
        mapping: title
build:
  writeStats: true
  
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
      anchorLineNos: false
      codeFences: true
      guessSyntax: false
      hl_Lines: ""
      hl_inline: false
      lineAnchors: ""
      lineNoStart: 1
      lineNos: true
      lineNumbersInTable: true
      noClasses: true
      noHl: false
      style: monokailight
      tabWidth: 4

outputs:
  home: ["HTML", "RSS", "JSON"]